'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property frm_EtatFenetre() As Integer
            Get
                Return CType(Me("frm_EtatFenetre"),Integer)
            End Get
            Set
                Me("frm_EtatFenetre") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\")>  _
        Public Property CheminRecherche() As String
            Get
                Return CType(Me("CheminRecherche"),String)
            End Get
            Set
                Me("CheminRecherche") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bInclureSousDossiers() As Boolean
            Get
                Return CType(Me("bInclureSousDossiers"),Boolean)
            End Get
            Set
                Me("bInclureSousDossiers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("*.*")>  _
        Public Property Filtre() As String
            Get
                Return CType(Me("Filtre"),String)
            End Get
            Set
                Me("Filtre") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bDateMin() As Boolean
            Get
                Return CType(Me("bDateMin"),Boolean)
            End Get
            Set
                Me("bDateMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bDateMax() As Boolean
            Get
                Return CType(Me("bDateMax"),Boolean)
            End Get
            Set
                Me("bDateMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DateMin() As Date
            Get
                Return CType(Me("DateMin"),Date)
            End Get
            Set
                Me("DateMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DateMax() As Date
            Get
                Return CType(Me("DateMax"),Date)
            End Get
            Set
                Me("DateMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bContient() As Boolean
            Get
                Return CType(Me("bContient"),Boolean)
            End Get
            Set
                Me("bContient") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MotARechercher() As String
            Get
                Return CType(Me("MotARechercher"),String)
            End Get
            Set
                Me("MotARechercher") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bCasse() As Boolean
            Get
                Return CType(Me("bCasse"),Boolean)
            End Get
            Set
                Me("bCasse") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property TypeEncodage() As Integer
            Get
                Return CType(Me("TypeEncodage"),Integer)
            End Get
            Set
                Me("TypeEncodage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bOuvrirBlocNotes() As Boolean
            Get
                Return CType(Me("bOuvrirBlocNotes"),Boolean)
            End Get
            Set
                Me("bOuvrirBlocNotes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10, 10")>  _
        Public Property frmPosition() As Global.System.Drawing.Point
            Get
                Return CType(Me("frmPosition"),Global.System.Drawing.Point)
            End Get
            Set
                Me("frmPosition") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("790, 590")>  _
        Public Property frmTaille() As Global.System.Drawing.Size
            Get
                Return CType(Me("frmTaille"),Global.System.Drawing.Size)
            End Get
            Set
                Me("frmTaille") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property FiltreExclusion() As String
            Get
                Return CType(Me("FiltreExclusion"),String)
            End Get
            Set
                Me("FiltreExclusion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("^(f)")>  _
        Public Property RaccourciBlocNotesRechercherCtrl_f() As String
            Get
                Return CType(Me("RaccourciBlocNotesRechercherCtrl_f"),String)
            End Get
            Set
                Me("RaccourciBlocNotesRechercherCtrl_f") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("%(c)")>  _
        Public Property RaccourciBlocNotesSensibleCasseAlt_c() As String
            Get
                Return CType(Me("RaccourciBlocNotesSensibleCasseAlt_c"),String)
            End Get
            Set
                Me("RaccourciBlocNotesSensibleCasseAlt_c") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("%(S)")>  _
        Public Property RaccourciBlocNotesOccurrSuivAlt_S() As String
            Get
                Return CType(Me("RaccourciBlocNotesOccurrSuivAlt_S"),String)
            End Get
            Set
                Me("RaccourciBlocNotesOccurrSuivAlt_S") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("%(F)")>  _
        Public Property RaccourciBlocNotesOccurrSuivAnglaisAlt_F() As String
            Get
                Return CType(Me("RaccourciBlocNotesOccurrSuivAnglaisAlt_F"),String)
            End Get
            Set
                Me("RaccourciBlocNotesOccurrSuivAnglaisAlt_F") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Notepad.exe")>  _
        Public Property ExeBlocNotes() As String
            Get
                Return CType(Me("ExeBlocNotes"),String)
            End Get
            Set
                Me("ExeBlocNotes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000")>  _
        Public Property DelaiMSec1OuvertureBlocNotes() As Integer
            Get
                Return CType(Me("DelaiMSec1OuvertureBlocNotes"),Integer)
            End Get
            Set
                Me("DelaiMSec1OuvertureBlocNotes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bBackgroundWorker() As Boolean
            Get
                Return CType(Me("bBackgroundWorker"),Boolean)
            End Get
            Set
                Me("bBackgroundWorker") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bLogBilan() As Boolean
            Get
                Return CType(Me("bLogBilan"),Boolean)
            End Get
            Set
                Me("bLogBilan") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bSignalerChaqueFichierBarreEtat() As Boolean
            Get
                Return CType(Me("bSignalerChaqueFichierBarreEtat"),Boolean)
            End Get
            Set
                Me("bSignalerChaqueFichierBarreEtat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.01")>  _
        Public Property DelaiAffichageBarreMsgSec() As Single
            Get
                Return CType(Me("DelaiAffichageBarreMsgSec"),Single)
            End Get
            Set
                Me("DelaiAffichageBarreMsgSec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.25")>  _
        Public Property DelaiAffichageListeFichiersSec() As Single
            Get
                Return CType(Me("DelaiAffichageListeFichiersSec"),Single)
            End Get
            Set
                Me("DelaiAffichageListeFichiersSec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("350")>  _
        Public Property TailleColChemin() As Integer
            Get
                Return CType(Me("TailleColChemin"),Integer)
            End Get
            Set
                Me("TailleColChemin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property TailleColTailleTxt() As Integer
            Get
                Return CType(Me("TailleColTailleTxt"),Integer)
            End Get
            Set
                Me("TailleColTailleTxt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("120")>  _
        Public Property TailleColDate() As Integer
            Get
                Return CType(Me("TailleColDate"),Integer)
            End Get
            Set
                Me("TailleColDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("120")>  _
        Public Property TailleColDateAcces() As Integer
            Get
                Return CType(Me("TailleColDateAcces"),Integer)
            End Get
            Set
                Me("TailleColDateAcces") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bTailleMin() As Boolean
            Get
                Return CType(Me("bTailleMin"),Boolean)
            End Get
            Set
                Me("bTailleMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bTailleMax() As Boolean
            Get
                Return CType(Me("bTailleMax"),Boolean)
            End Get
            Set
                Me("bTailleMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TailleMin() As String
            Get
                Return CType(Me("TailleMin"),String)
            End Get
            Set
                Me("TailleMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000000")>  _
        Public Property TailleMax() As String
            Get
                Return CType(Me("TailleMax"),String)
            End Get
            Set
                Me("TailleMax") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.VBFileFind.My.MySettings
            Get
                Return Global.VBFileFind.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
